sudo: true
dist: precise
language: c

addons:
  apt:
    packages:
    # GHC
    - libgmp-dev
    # Selenium
    - xvfb

cache:
  directories:
    - $HOME/.stack
    - .stack-work

matrix:
  include:
    - env: ARGS=""
    - env: ARGS="--resolver nightly"

  allow_failures:
    - env: ARGS="--resolver nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

- wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- chmod +x chromedriver
- sudo mv -f chromedriver /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver

before_script:
- sh -e /etc/init.d/xvfb start
- export DISPLAY=:99.0
- travis_retry wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
- java -jar selenium-server-standalone-2.53.1.jar 2> /dev/null &
- sleep 30

script:
 - stack $ARGS --no-terminal --install-ghc build --test
 - scripts/test-official.sh $ARGS

